
Server:
  port: 8000

Spring:
  application:
    name: Task-GATEWAY
  cloud:
    gateway:
        routes:
          - id: USER-SERVICE
            uri:
              lb://USER-SERVICE
            predicates:
              - Path=/auth/**, /users/**, /api/users/**, /

          - id: TASK-SERVICE
            uri:
              lb://TASK-SERVICE
            predicates:
              - Path=/api/tasks/**, /tasks/**

          - id: TASK-SUBMISSION
            uri:
              lb://TASK-SUBMISSION
            predicates:
              - Path=/api/submissions/**,/submissions/**


        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    ServiceUrl:
      defaultZone: http://localhost:8004/eureka/
